#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK_DIR="$ROOT_DIR/.githooks"
ENV_FILE="$HOOK_DIR/.codex.env"

mkdir -p "$HOOK_DIR"

resolve_codex_bin() {
  if command -v codex >/dev/null 2>&1; then
    command -v codex
    return 0
  fi

  local latest=""
  latest="$(ls -d "$HOME"/.vscode/extensions/openai.chatgpt-*/bin/macos-aarch64/codex 2>/dev/null | sort -V | tail -n 1 || true)"
  if [[ -n "$latest" ]]; then
    printf "%s\n" "$latest"
    return 0
  fi

  return 1
}

CODEX_BIN="$(resolve_codex_bin || true)"
if [[ -z "$CODEX_BIN" ]]; then
  echo "[codex:setup] codex binary not found." >&2
  echo "[codex:setup] Install/enable Codex CLI first, then rerun: npm run hooks:install" >&2
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Generated by npm run codex:setup
export CODEX_BIN="$CODEX_BIN"
EOF

chmod 600 "$ENV_FILE"
chmod +x "$HOOK_DIR/pre-commit" "$HOOK_DIR/pre-push"

echo "[codex:setup] CODEX_BIN=$CODEX_BIN"
echo "[codex:setup] wrote $ENV_FILE"

